version: '3.1'
services:
  cobbs.ai:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: STANDARD
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "14000:14000"
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: "true"
      DOCKER_DB_HOST: db
      runmode: prod
      dataSourceName: "root:${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}@tcp(db:3306)/"
      issuer: "${COBBSAI_ISSUER:?COBBSAI_ISSUER is required}"
      casdoorEndpoint: "${COBBSAI_ISSUER:?COBBSAI_ISSUER is required}"
      clientId: "${COBBSAI_CLIENT_ID:?COBBSAI_CLIENT_ID is required}"
      clientSecret: "${COBBSAI_CLIENT_SECRET:?COBBSAI_CLIENT_SECRET is required}"
      casdoorOrganization: "${COBBSAI_ORGANIZATION:?COBBSAI_ORGANIZATION is required}"
      casdoorApplication: "${COBBSAI_APPLICATION:?COBBSAI_APPLICATION is required}"
    volumes:
      - ./conf:/conf/
  db:
    restart: always
    image: mysql:8.0.25
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}"
    volumes:
      - /usr/local/docker/mysql:/var/lib/mysql
