appname = cobbs.ai
httpport = 14000
runmode = prod
driverName = mysql
dataSourceName =
dbName = casibase
redisEndpoint =
isDemoMode = false
issuer =
clientId =
clientSecret =
ipParsingMode = ""
parentDbName = ""
socks5Proxy = "127.0.0.1:10808"
logConfig = {"adapter":"file", "filename": "logs/cobbs.ai.log", "maxdays":99999, "perm":"0770"}
